apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  name: gardener-test-iam-role
  labels:
    role: gardener-teest-iam-role
    crossplane-demo: aws-levelup-managed-resources
spec:
  forProvider:
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": {
              "Service": [
                  "s3.amazonaws.com"
              ]
            },
            "Action": "sts:AssumeRole"
          }
        ]
      }
  providerConfigRef:
    name: gov
