apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xharbors.k8s.xp.sapns2.io
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: xp.sapns2.io/v1alpha1
    kind: XHarbors
  resources:
    - name: harborRelease
      base:
        apiVersion: helm.crossplane.io/v1beta1
        kind: Release
        spec:
          forProvider:
            chart:
              name: harbor
              repository: https://helm.goharbor.io
            namespace: harbor
            #set:
            #  - name: param1
            #    value: value2
            values:
              nginx:
                image:
                  repository: 029168290193.dkr.ecr.us-gov-west-1.amazonaws.com/nginx-photon
              portal:
                image:
                  repository: 029168290193.dkr.ecr.us-gov-west-1.amazonaws.com/harbor-portal
              core:
                image:
                  repository: 029168290193.dkr.ecr.us-gov-west-1.amazonaws.com/harbor-core
              jobservice:
                image:
                  repository: 029168290193.dkr.ecr.us-gov-west-1.amazonaws.com/harbor-jobservice
              registry:
                image:
                  repository: 029168290193.dkr.ecr.us-gov-west-1.amazonaws.com/registry-photon
                controller:
                  image:
                    repository: 029168290193.dkr.ecr.us-gov-west-1.amazonaws.com/harbor-registryctl
              trivy:
                image:
                  repository: 029168290193.dkr.ecr.us-gov-west-1.amazonaws.com/trivy-adapter-photon
              database:
                internal:
                  image:
                    repository: 029168290193.dkr.ecr.us-gov-west-1.amazonaws.com/harbor-db
              redis:
                internal:
                  image:
                    repository: 029168290193.dkr.ecr.us-gov-west-1.amazonaws.com/redis-photon
              exporter:
                image:
                  repository: 029168290193.dkr.ecr.us-gov-west-1.amazonaws.com/harbor-exporter
              expose:
                type: clusterIP
                tls:
                  auto:
                    commonName: "ns2-test-harbor"
          providerConfigRef:
            name: helm-provider
      patches:
        - fromFieldPath: spec.id
          toFieldPath: spec.providerConfigRef.name
        - fromFieldPath: spec.id
          toFieldPath: metadata.name
          transforms:
            - string:
                fmt: '%s-harbor'
                type: Format
              type: string