apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xharbors.xp.sapns2.io
spec:
  group: xp.sapns2.io
  names:
    kind: XHarbors
    plural: xharbors
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              id:
                type: string
                description: ID of this environment to be used for naming
            required:
            - id
          status:
            description: A status represents the observed state
            properties:
              misc:
                description: Freeform field containing status information for eks
                type: object
                x-kubernetes-preserve-unknown-fields: true
            type: object
