apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xnetworks.xp.sapns2.io
spec:
  group: xp.sapns2.io
  names:
    kind: XNetwork
    plural: xnetworks
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                id:
                  type: string
                  description: ID of this Network that other objects will use to refer to it.
                region:
                  type: string
                  description: aws region to use
              required:
                - id
                - region
            status:
              description: List of status items
              properties:
                endpointSubnets:
                  type: array
                  description: subnets to use for endpoints
                  items:
                    type: string
              type: object