#apiVersion: pkg.crossplane.io/v1
#kind: Provider
#metadata:
#  name: provider-aws-s3
#spec:
#  package: xpkg.upbound.io/upbound/provider-aws-s3:v1.4.0
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-ec2
spec:
  package: xpkg.upbound.io/upbound/provider-aws-ec2:v1.10.0
---
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: aws-config
spec:
  podSecurityContext:
    fsGroup: 2000
  env:
    - name: AWS_REGION
      value: us-gov-west-1
    - name: AWS_DEFAULT_REGION
      value: us-gov-west-1
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-iam
spec:
  #package: xpkg.upbound.io/upbound/provider-aws-iam:v1.1.0
  package: xpkg.upbound.io/upbound/provider-aws-iam:v1.10.0
  controllerConfigRef:
    name: aws-config
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-eks
spec:
  package: xpkg.upbound.io/upbound/provider-aws-eks:v1.10.0
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-ecr
spec:
  package: xpkg.upbound.io/upbound/provider-aws-ecr:v1.8.0