apiVersion: iam.aws.upbound.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: xp-test-rpa
spec:
  forProvider:
    policyArn: arn:aws-us-gov:iam::aws:policy/AmazonEKSClusterPolicy
    roleSelector:
      matchLabels:
        role: xp-test-controlplane
