apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  name: xp-test-controlplane
  labels:
    role: xp-test-controlplane
spec:
  providerConfigRef:
    name: gov
  forProvider:
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Effect": "Allow",
                "Principal": {
                    "Service": [
                        "eks.amazonaws.com"
                    ]
                },
                "Action": [
                    "sts:AssumeRole"
                ]
            }
        ]
      }